# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Biomechanical Analysis using Python and Kinetics Toolkit
author: Félix Chénier
copyright: 2020-2024
#logo: 'logo.png'

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: cache
#  execute_notebooks: force

parse:
  myst_enable_extensions:  # default extensions to enable in the myst parser. See https://myst-parser.readthedocs.io/en/latest/using/syntax-optional.html
    # - amsmath
    - colon_fence
    # - deflist
    - dollarmath
    # - html_admonition
    - html_image
    - linkify
    # - replacements
    # - smartquotes
    - substitution
    - tasklist

  myst_substitutions:

    matplotlib: "[Matplotlib](https://matplotlib.org)"
    pyplot: "[pyplot](https://matplotlib.org/stable/api/pyplot_summary.html)"
    plt_plot: "[plt.plot](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.plot.html)"
    plt_scatter: "[plt.scatter](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.scatter.html)"
    plt_fill_between: "[plt.fill_between](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.fill_between.html)"
    plt_imshow: "[plt.imshow](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.imshow.html)"
    plt_errorbar: "[plt.errorbar](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.errorbar.html)"
    plt_bar: "[plt.bar](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.bar.html)"
    plt_show: "[plt.show](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.show.html)"
    plt_xlabel: "[plt.xlabel](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.xlabel.html)"
    plt_ylabel: "[plt.ylabel](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.ylabel.html)"
    plt_title: "[plt.title](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.title.html)"
    plt_legend: "[plt.legend](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.legend.html)"
    plt_subplot: "[plt.subplot](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.subplot.html)"
    plt_tight_layout: "[plt.tight_layout](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.tight_layout.html)"
    plt_figure: "[plt.figure](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.figure.html)"
    plt_clf: "[plt.clf](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.clf.html)"
    plt_axis: "[plt.axis](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.axis.html)"
    plt_grid: "[plt.grid](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.grid.html)"
    plt_ginput: "[plt.ginput](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.ginput.html)"

    numpy: "[NumPy](https://numpy.org)"
    np_array: "[np.array](https://numpy.org/doc/stable/reference/generated/numpy.array.html)"
    np_ones: "[np.ones](https://numpy.org/doc/stable/reference/generated/numpy.ones.html)"
    np_zeros: "[np.zeros](https://numpy.org/doc/stable/reference/generated/numpy.zeros.html)"
    np_nonzero: "[np.nonzero](https://numpy.org/doc/stable/reference/generated/numpy.nonzero.html)"
    np_arange: "[np.arange](https://numpy.org/doc/stable/reference/generated/numpy.arange.html)"
    np_linspace: "[np.linspace](https://numpy.org/doc/stable/reference/generated/numpy.linspace.html)"
    np_ix_: "[np.ix_](https://numpy.org/doc/stable/reference/generated/numpy.ix_.html)"
    np_broadcasting: "[broadcasting](https://numpy.org/doc/stable/user/basics.broadcasting.html)"
    np_sin: "[np.sin](https://numpy.org/doc/stable/reference/generated/numpy.sin.html)"
    np_cos: "[np.cos](https://numpy.org/doc/stable/reference/generated/numpy.cos.html)"
    np_tan: "[np.tan](https://numpy.org/doc/stable/reference/generated/numpy.tan.html)"
    np_arcsin: "[np.arcsin](https://numpy.org/doc/stable/reference/generated/numpy.arcsin.html)"
    np_arccos: "[np.arccos](https://numpy.org/doc/stable/reference/generated/numpy.arccos.html)"
    np_arctan: "[np.arctan](https://numpy.org/doc/stable/reference/generated/numpy.arctan.html)"
    np_arctan2: "[np.arctan2](https://numpy.org/doc/stable/reference/generated/numpy.arctan2.html)"
    np_sqrt: "[np.sqrt](https://numpy.org/doc/stable/reference/generated/numpy.sqrt.html)"
    np_abs: "[np.abs](https://numpy.org/doc/stable/reference/generated/numpy.absolute.html)"
    np_rad2deg: "[np.rad2deg](https://numpy.org/doc/stable/reference/generated/numpy.rad2deg.html)"
    np_deg2rad: "[np.deg2rad](https://numpy.org/doc/stable/reference/generated/numpy.deg2rad.html)"
    np_pi: "[np.pi](https://numpy.org/doc/stable/reference/constants.html#numpy.pi)"
    np_nan: "[np.nan](https://numpy.org/doc/stable/reference/constants.html#numpy.nan)"
    np_inf: "[np.inf](https://numpy.org/doc/stable/reference/constants.html#numpy.inf)"
    np_isnan: "[np.isnan](https://numpy.org/doc/stable/reference/generated/numpy.isnan.html)"
    np_isinf: "[np.isinf](https://numpy.org/doc/stable/reference/generated/numpy.isinf.html)"
    np_sum: "[np.sum](https://numpy.org/doc/stable/reference/generated/numpy.sum.html)"
    np_mean: "[np.mean](https://numpy.org/doc/stable/reference/generated/numpy.mean.html)"
    np_min: "[np.min](https://numpy.org/doc/stable/reference/generated/numpy.amin.html)"
    np_max: "[np.max](https://numpy.org/doc/stable/reference/generated/numpy.amax.html)"
    np_std: "[np.std](https://numpy.org/doc/stable/reference/generated/numpy.std.html)"
    np_median: "[np.median](https://numpy.org/doc/stable/reference/generated/numpy.median.html)"
    np_quantile: "[np.quantile](https://numpy.org/doc/stable/reference/generated/numpy.quantile.html)"
    np_nansum: "[np.nansum](https://numpy.org/doc/stable/reference/generated/numpy.nansum.html)"
    np_nanmean: "[np.nanmean](https://numpy.org/doc/stable/reference/generated/numpy.nanmean.html)"
    np_nanmin: "[np.nanmin](https://numpy.org/doc/stable/reference/generated/numpy.nanmin.html)"
    np_nanmax: "[np.nanmax](https://numpy.org/doc/stable/reference/generated/numpy.nanmax.html)"
    np_nanstd: "[np.nanstd](https://numpy.org/doc/stable/reference/generated/numpy.nanstd.html)"
    np_nanmedian: "[np.nanmedian](https://numpy.org/doc/stable/reference/generated/numpy.nanmedian.html)"
    np_nanquantile: "[np.nanquantile](https://numpy.org/doc/stable/reference/generated/numpy.nanquantile.html)"
    np_newaxis: "[np.newaxis](https://numpy.org/doc/stable/reference/constants.html#numpy.newaxis)"

    ndarray: "[ndarray](https://numpy.org/doc/stable/reference/arrays.ndarray.html)"
    ndarray_shape: "[shape](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.shape.html)"
    ndarray_tolist: "[tolist](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.tolist.html)"
    ndarray_copy: "[copy](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.copy.html)"

    pandas: "[Pandas](https://pandas.pydata.org/)"
    pd_series: "[Series](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.html)"
    pd_dataframe: "[DataFrame](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.html)"
    pd_read_csv: "[pd.read_csv](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html)"
    dataframe_to_csv: "[to_csv](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_csv.html)"

    ezc3d: "[ezc3d](https://github.com/pyomeca/ezc3d)"

    "stub": |
      ```{admonition} Section in development
      :class: admonition-stub
      This section is still in heavy development. Your [suggestions](dev_contributing.md) are welcome.
      ```
    "incomplete": |
      ```{admonition} Incomplete section
      Some elements of this section are incomplete or out of date. Please feel free to [contribute](dev_contributing.md).
      ```
    "dev": |
      ```{warning}
      This section refers to unstable code. This code may not be tested, and the whole API and behaviour is expected to change in the future. Do not use this code for your research.
      ```


repository:
  url: https://github.com/felixchenier/kineticstoolkit

html:
#  favicon                   : ''  # A path to a favicon image
  use_multitoc_numbering    : true   # Continuous numbering across parts/chapters
  extra_footer              : ""  # Will be displayed underneath the footer.
  google_analytics_id       : ""  # A GA id that can be used to track book views.
  home_page_in_navbar       : false  # Whether to include your home page in the left Navigation Bar
  baseurl                   : "https://kineticstoolkit.uqam.ca/doc/"  # The base URL where your book will be hosted. Used for creating image previews and social links. e.g.: https://mypage.com/mybook/
  comments:
    hypothesis              : false
    utterances              : false
  announcement              : "" # A banner announcement at the top of the site.
  show_navbar_depth         : 3

latex:
  latex_engine              : pdflatex  # one of 'pdflatex', 'xelatex' (recommended for unicode), 'luatex', 'platex', 'uplatex'
  use_jupyterbook_latex     : true # use sphinx-jupyterbook-latex for pdf builds as default
  latex_elements:
    pxunit: "0.3cm"



#html_theme_options:
#  use_download_button       : true  # Add a button in the header to download the source file of the page
#  use_repository_button     : true  # Whether to add a link to your repository button
#  use_issues_button         : true  # Whether to add an "open an issue" button
#  repository_url            : https://github.com/felixchenier/kineticstoolkit
#  show_toc_level            : -1  # Sidebar local contents
#  collapse_navigation       : True
#  navigation_depth          : 4
#  extra_footer: "This website is built using <a href='https://jupyterbook.org'>jupyter-book</a>."

sphinx:
  extra_extensions:
  - 'sphinx.ext.autodoc'     # Document objects using docstrings in API
  - 'sphinx.ext.autosummary' # Generate summary table pages (for autodoc)
  - 'sphinx.ext.napoleon'    # Parse numpy-style docstrings (for autodoc)
  - 'sphinx.ext.viewcode'
  - 'custom-directives'
  - 'sphinx_sitemap'
  - 'myst_nb'
  - 'sphinxext.opengraph'    # Generate metadata for social media

  config:
#    html_baseurl: 'https://kineticstoolkit.uqam.ca/doc'
    add_module_names: False

    autosummary_generate: True

    autodoc_typehints: description
    autodoc_type_aliases:
        'ArrayLike': 'ArrayLike'
        'kineticstoolkit._timeseries.TimeSeries': 'TimeSeries'
        'pandas.core.frame.DataFrame': 'DataFrame'
        'pandas.core.frame.Series': 'Series'
    suppress_warnings:
        - 'etoc.toctree'
        - 'etoc.tableofcontents'
    napoleon_google_docstring: False
    napoleon_numpy_docstring: True
    napoleon_include_init_with_doc: False
    napoleon_include_private_with_doc: False
    napoleon_include_special_with_doc: False
    napoleon_use_admonition_for_examples: False
    napoleon_use_admonition_for_notes: True
    napoleon_use_admonition_for_references: True
    napoleon_use_ivar: False
    napoleon_use_param: True
    napoleon_use_rtype: True

    ogp_site_url: "https://kineticstoolkit.uqam.ca/doc/"
    ogp_description_length: 200
    ogp_site_name: "Kinetics Toolkit"
    # ogp_social_cards:         Configuration for automatically creating social media card PNGs for each page. For more information, see the social media cards docs.
    ogp_image: "https://kineticstoolkit.uqam.ca/doc/_static/logo-social.png"
    ogp_image_alt: "Kinetics Toolkit Logo"
    ogp_type: "image/png"
    ogp_custom_meta_tags:
        - "<meta property='og:image:width' content=500 />"
        - "<meta property='og:image:height' content=264 />"
    # ogp_enable_meta_description        This is not required. When True, generates <meta name="description" content="..."> from the page.
    
    html_favicon: favicon.ico
    html_theme_options:
        collapse_navigation: True
        navigation_depth: 4
        logo:
            'image_light': '_static/logo.png'
            'image_dark': '_static/logo-dark.png'
        extra_footer: "This website is built using <a href='https://jupyterbook.org'>jupyter-book</a>."

    exclude_patterns:
      - '_build'
      - 'Thumbs.db'
      - '.DS_Store'
      - '.ipynb_checkpoints'
      - 'api/external.*'
      - 'api/ktk.external.*'
      - 'api/ktk.pushrimkinetics*'
      - 'toc.md'
      - '_templates'  # Should be the last line of the file (-Felix)
